version: "3.1"

services:
  db:
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: fei2022
      MYSQL_ROOT_PASSWORD: fei2022
    ports:
      - "4000:3306"
    volumes:
    - ./mysqldata:/var/lib/mysql
  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: fei2022
    ports:
      - 8001:80

  app:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
    environment: 
      DDBB_DATABASE: fei2022
      DDBB_PASSWORD: fei2022
      DDBB_HOST: db
      PHP_USER_ID: 1000
    ports:
      - 8000:80
